### ISSUE TITLE
RFC: To-do list

### ISSUE THREAD

**Issue by HadalFauna** [retrofor/HydroRoll#37]
### Discussed in https://github.com/orgs/HydroRoll-Team/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **HadalFauna** August 11, 2023</sup>
- [ ] HydroRoll-Team/HydroRollCore#9
- [ ] HydroRoll-Team/HydroRollCore#11
- [ ] HydroRoll-Team/HydroRollCore#10
- [ ] HydroRoll-Team/HydroRollCore#8
- [ ] HydroRoll-Team/HydroRoll-site#4
</div>
